#!/usr/bin/env python3
"""Assemble V2 CSVs from independently verified facts. No docking/AUROC."""
from __future__ import annotations

import csv
from pathlib import Path

QA = Path("/tmp/pr39_fiveseed/Dual_Target_Docking/reruns/UNIFORM_RERUN_V4_2_20260921/13_qa")

# Pocket cutoff is NOT frozen in protocol (only BOX_PAD_A=5.0). All three reported.
CUTOFFS = (4.0, 4.5, 5.0)

# Pre-declared bins (declared before RMSD inspection in alt_receptor_fact_verify_v2.py)
# NEAR <1.5; INTERMEDIATE <=3.0; FAR >3.0 Å pocket CA RMSD

RMSD = {
    # (target, alt, cutoff): (bb, sc, n_pocket, n_common, completeness, n_rot, pert)
    ("EGFR", "1XKK", 4.0): (0.557, 0.845, 21, 21, 1.0, 0, "NEAR"),
    ("EGFR", "1XKK", 4.5): (0.565, 0.827, 25, 25, 1.0, 0, "NEAR"),
    ("EGFR", "1XKK", 5.0): (0.822, 1.209, 27, 27, 1.0, 1, "NEAR"),
    ("HER2", "3PP0", 4.0): (6.468, 6.679, 19, 19, 1.0, 17, "FAR"),
    ("HER2", "3PP0", 4.5): (7.303, 7.356, 23, 23, 1.0, 20, "FAR"),
    ("HER2", "3PP0", 5.0): (7.500, 7.467, 26, 26, 1.0, 23, "FAR"),
    ("JAK1", "4EI4", 4.0): (0.724, 1.102, 19, 19, 1.0, 2, "NEAR"),
    ("JAK1", "4EI4", 4.5): (0.706, 1.077, 20, 20, 1.0, 2, "NEAR"),
    ("JAK1", "4EI4", 5.0): (0.698, 1.045, 22, 22, 1.0, 2, "NEAR"),
    ("JAK2", "8BM2", 4.0): (0.628, 0.885, 16, 16, 1.0, 0, "NEAR"),
    ("JAK2", "8BM2", 4.5): (0.589, 0.812, 19, 19, 1.0, 0, "NEAR"),
    ("JAK2", "8BM2", 5.0): (1.636, 3.539, 25, 25, 1.0, 2, "INTERMEDIATE"),
    ("PIK3CA", "4L2Y", 4.0): (0.250, 0.798, 13, 13, 1.0, 0, "NEAR"),
    ("PIK3CA", "4L2Y", 4.5): (0.278, 0.752, 18, 18, 1.0, 0, "NEAR"),
    ("PIK3CA", "4L2Y", 5.0): (0.294, 0.707, 21, 21, 1.0, 0, "NEAR"),
    ("PIK3CA", "4JPS", 4.0): (0.541, 0.978, 13, 13, 1.0, 0, "NEAR"),
    ("PIK3CA", "4JPS", 4.5): (0.611, 0.973, 18, 18, 1.0, 0, "NEAR"),
    ("PIK3CA", "4JPS", 5.0): (0.583, 0.914, 21, 21, 1.0, 0, "NEAR"),
    ("PIK3CA", "5XGH", 4.0): (0.591, 0.915, 13, 13, 1.0, 0, "NEAR"),
    ("PIK3CA", "5XGH", 4.5): (0.569, 0.859, 18, 18, 1.0, 0, "NEAR"),
    ("PIK3CA", "5XGH", 5.0): (0.523, 0.803, 21, 21, 1.0, 0, "NEAR"),
    ("PIK3CA", "5DXT", 4.0): (4.931, 4.299, 13, 13, 1.0, 13, "FAR"),
    ("PIK3CA", "5DXT", 4.5): (5.784, 4.791, 18, 18, 1.0, 18, "FAR"),
    ("PIK3CA", "5DXT", 5.0): (5.752, 4.839, 21, 21, 1.0, 21, "FAR"),
    ("mTOR", "4JT5", 4.0): (0.734, 1.565, 11, 11, 1.0, 1, "NEAR"),
    ("mTOR", "4JT5", 4.5): (0.722, 1.510, 17, 17, 1.0, 1, "NEAR"),
    ("mTOR", "4JT5", 5.0): (0.722, 1.510, 17, 17, 1.0, 1, "NEAR"),
    ("mTOR", "4JSX", 4.0): (0.345, 0.622, 11, 11, 1.0, 0, "NEAR"),
    ("mTOR", "4JSX", 4.5): (0.354, 0.590, 17, 17, 1.0, 0, "NEAR"),
    ("mTOR", "4JSX", 5.0): (0.354, 0.590, 17, 17, 1.0, 0, "NEAR"),
    ("mTOR", "4JSV", 4.0): (0.306, 0.680, 11, 11, 1.0, 0, "NEAR"),
    ("mTOR", "4JSV", 4.5): (0.295, 0.863, 17, 17, 1.0, 0, "NEAR"),
    ("mTOR", "4JSV", 5.0): (0.295, 0.863, 17, 17, 1.0, 0, "NEAR"),
    ("AChE", "4EY6", 4.0): (0.306, 0.933, 15, 15, 1.0, 0, "NEAR"),
    ("AChE", "4EY6", 4.5): (0.320, 0.916, 19, 19, 1.0, 0, "NEAR"),
    ("AChE", "4EY6", 5.0): (0.306, 0.868, 21, 21, 1.0, 0, "NEAR"),
    ("BChE", "1P0M", 4.0): (0.155, 0.332, 11, 11, 1.0, 0, "NEAR"),
    ("BChE", "1P0M", 4.5): (0.170, 0.479, 15, 15, 1.0, 0, "NEAR"),
    ("BChE", "1P0M", 5.0): (0.162, 0.473, 16, 16, 1.0, 0, "NEAR"),
    ("F2", "3SHC", 4.0): (0.205, 0.870, 20, 29, "CONFLICT_ncom_gt_npocket_147_insertion", 0, "NEAR"),
    ("F2", "3SHC", 4.5): (0.201, 0.827, 22, 31, "CONFLICT_ncom_gt_npocket_147_insertion", 0, "NEAR"),
    ("F2", "3SHC", 5.0): (0.201, 0.827, 22, 31, "CONFLICT_ncom_gt_npocket_147_insertion", 0, "NEAR"),
    ("F10", "2Y5F", 4.0): (0.143, 0.725, 17, 17, 1.0, 0, "NEAR"),
    ("F10", "2Y5F", 4.5): (0.141, 0.706, 19, 19, 1.0, 0, "NEAR"),
    ("F10", "2Y5F", 5.0): (0.151, 0.687, 21, 21, 1.0, 0, "NEAR"),
    ("PPARG", "7AWC", 4.0): (5.370, 4.611, 16, 16, 1.0, 14, "FAR"),
    ("PPARG", "7AWC", 4.5): (5.623, 5.253, 22, 22, 1.0, 20, "FAR"),
    ("PPARG", "7AWC", 5.0): (5.610, 5.275, 23, 23, 1.0, 21, "FAR"),
    ("PPARA", "6KAX", 4.0): (0.130, 0.255, 19, 19, 1.0, 0, "NEAR"),
    ("PPARA", "6KAX", 4.5): (0.147, 0.244, 24, 24, 1.0, 0, "NEAR"),
    ("PPARA", "6KAX", 5.0): (0.144, 0.240, 26, 26, 1.0, 0, "NEAR"),
    ("PPARD", "5U46", 4.0): (0.519, 0.788, 21, 21, 1.0, 0, "NEAR"),
    ("PPARD", "5U46", 4.5): (0.495, 0.857, 25, 25, 1.0, 0, "NEAR"),
    ("PPARD", "5U46", 5.0): (0.494, 0.837, 28, 28, 1.0, 0, "NEAR"),
}

# V1 inventory (hard-pass includes primary). Not re-searched in V2.
V1_INV = {
    "EGFR": (393, 304, 303),
    "HER2": (63, 6, 5),
    "JAK1": (52, 45, 44),
    "JAK2": (171, 109, 108),
    "TYK2": (52, 29, 28),
    "PIK3CA": (138, 103, 102),
    "mTOR": (73, 37, 36),
    "AChE": (79, 65, 64),
    "BChE": (111, 104, 103),
    "F2": (479, 342, 341),
    "F10": (192, 135, 134),
    "PPARG": (380, 354, 353),
    "PPARA": (79, 78, 77),
    "PPARD": (56, 54, 53),
}

UNP = {
    "EGFR": "P00533", "HER2": "P04626", "JAK1": "P23458", "JAK2": "O60674",
    "TYK2": "P29597", "PIK3CA": "P42336", "mTOR": "P42345", "AChE": "P22303",
    "BChE": "P06276", "F2": "P00734", "F10": "P00742", "PPARG": "P37231",
    "PPARA": "Q07869", "PPARD": "Q03181",
}
PRI = {
    "EGFR": "3POZ", "HER2": "3RCD", "JAK1": "6N7A", "JAK2": "8BXH", "TYK2": "3LXP",
    "PIK3CA": "4L23", "mTOR": "4JT6", "AChE": "4EY7", "BChE": "4BDS", "F2": "4UDW",
    "F10": "2JKH", "PPARG": "9V8H", "PPARA": "6LXA", "PPARD": "5U3Q",
}


def wcsv(path, rows):
    fields = []
    for r in rows:
        for k in r:
            if k not in fields:
                fields.append(k)
    with path.open("w", encoding="utf-8", newline="") as h:
        w = csv.DictWriter(h, fieldnames=fields, extrasaction="ignore", lineterminator="\n")
        w.writeheader()
        w.writerows(rows)


def main():
    facts = [
        dict(target="EGFR", pdb="3POZ", role="PRIMARY", is_primary="YES", uniprot="P00533", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="1.50", doi="10.1074/jbc.M110.206193", pmid="21454582",
             title="EGFR Kinase domain complexed with tak-285",
             construct_auth="A:696-1022", construct_uniprot="696-1022", chain_auth="A", chain_label="A",
             ligand_ccd="03P", ligand_chain_copy="A:1023/label E", ligand_same_canonical_site="YES_PRIMARY_DEFINITION",
             n_mutation="0", mutations="NONE_IN_struct_ref_seq_dif_and_entity.pdbx_mutation",
             mutation_in_unified_pocket="NO", ptm="NONE_IN_pdbx_struct_mod_residue", phosphorylation="NONE",
             disulfide="0", partner="NONE", retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1", altloc="NO", n_unobs_res="34", n_unobs_atom="0",
             pocket_unobs="N-term/A-loop/C-term unobs listed; pocket atoms not individually enumerated as missing",
             clashscore="3.30", percent_rama_outliers="0.35", percent_rota_outliers="1.15",
             validation_source="wwPDB validation XML",
             paper="Aertgeerts 2011 JBC; EGFR/TAK-285 inactive-like alphaC displacement vs active EGFR",
             conflicts="NONE", historically_exposed="NO", notes="V4.2 primary"),
        dict(target="EGFR", pdb="1XKK", role="ALTERNATIVE", is_primary="NO", uniprot="P00533", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="2.40", doi="10.1158/0008-5472.CAN-04-1168", pmid="15374980",
             title="EGFR kinase domain complexed with a quinazoline inhibitor- GW572016",
             construct_auth="A:695-1022", construct_uniprot="695-1022", chain_auth="A", chain_label="A",
             ligand_ccd="FMM", ligand_chain_copy="A", ligand_same_canonical_site="YES_ATP_SITE",
             n_mutation="0", mutations="NONE; 23 N-terminal expression-tag residues in struct_ref_seq_dif",
             mutation_in_unified_pocket="NO", ptm="NONE_IN_pdbx_struct_mod_residue", phosphorylation="NONE",
             disulfide="0", partner="NONE", retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1", altloc="NO", n_unobs_res="63", n_unobs_atom="83",
             pocket_unobs="63 unobs residues including N-term tag; pocket completeness 1.0 at 4.0/4.5/5.0",
             clashscore="13.85", percent_rama_outliers="1.08", percent_rota_outliers="0.00",
             validation_source="wwPDB validation XML",
             paper="Wood 2004 Cancer Res; lapatinib/GW572016 type II EGFR kinase",
             conflicts="N-term His-tag/expression residues vs 3POZ (3POZ has no declared tags)",
             historically_exposed="YES_V1_DISCUSSION", notes="CLEAN-NEAR vs 3POZ"),
        dict(target="HER2", pdb="3RCD", role="PRIMARY", is_primary="YES", uniprot="P04626", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="3.21", doi="10.1021/jm2008634", pmid="22003817",
             title="HER2 Kinase Domain Complexed with TAK-285",
             construct_auth="A/B/C/D:713-1028_declared", construct_uniprot="713-1028_declared",
             chain_auth="A", chain_label="A",
             ligand_ccd="03P", ligand_chain_copy="A:9001 and C:9001", ligand_same_canonical_site="YES_PRIMARY_DEFINITION",
             n_mutation="0_declared", mutations="NONE_declared; residues 702-712 and C-term His-tag annotated as expression tag not mutation",
             mutation_in_unified_pocket="NO", ptm="NONE_IN_pdbx_struct_mod_residue", phosphorylation="NONE",
             disulfide="0", partner="NONE", retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="4", altloc="NO", n_unobs_res="248", n_unobs_atom="0",
             pocket_unobs="248 unobs residues across 4 copies; A-loop/N-term disordered in paper",
             clashscore="11.83", percent_rama_outliers="1.97", percent_rota_outliers="14.05",
             validation_source="wwPDB validation XML",
             paper="Ishikawa 2011 JMC TAK-285",
             conflicts="Deposited 340-aa sequence is identical to 3PP0 but 3RCD does not declare M706A/Q711L/M712L; 706/711/712 labeled expression tag (ALA/LEU/LEU) matching 3PP0 mutant residues",
             historically_exposed="NO", notes="V4.2 primary; low resolution; high rota outliers"),
        dict(target="HER2", pdb="3PP0", role="ALTERNATIVE", is_primary="NO", uniprot="P04626", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="2.25", doi="10.1074/jbc.M110.206193", pmid="21454582",
             title="Crystal Structure of the Kinase domain of Human HER2 (erbB2).",
             construct_auth="A/B:706-1009_declared", construct_uniprot="706-1009_declared",
             chain_auth="B", chain_label="B",
             ligand_ccd="03Q", ligand_chain_copy="A:1 and B:2", ligand_same_canonical_site="YES_ATP_SITE",
             n_mutation="3", mutations="M706A; Q711L; M712L (both chains)",
             mutation_in_unified_pocket="NO_not_in_3RCD_4.5A_set_726-1004",
             ptm="NONE_IN_pdbx_struct_mod_residue", phosphorylation="NONE",
             disulfide="0", partner="NONE_in_extract; crystal is kinase dimer",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="2", altloc="YES", n_unobs_res="94", n_unobs_atom="1",
             pocket_unobs="pocket completeness 1.0; A-loop Asp880-Gly881 disordered in paper",
             clashscore="4.92", percent_rama_outliers="0.35", percent_rota_outliers="4.09",
             validation_source="wwPDB validation XML",
             paper="Aertgeerts 2011 JBC; HER2/SYR127063 dimer; alphaC flexibility; inactive-like missing Lys753-Glu770 salt bridge",
             conflicts="1) construct range 706-1009 vs 3RCD 713-1028 but entity_poly sequences identical (340 aa). 2) mutations declared here vs expression-tag labeling on 3RCD for same N-terminal amino acids. 3) ligand 03Q vs 03P (related series not identical).",
             historically_exposed="YES_V1_DISCUSSION", notes="MODERATE-FAR; alphaC CA RMSD 8.61 A vs 3RCD-A"),
        dict(target="JAK1", pdb="6N7A", role="PRIMARY", is_primary="YES", uniprot="P23458", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="1.33", doi="10.1016/j.bmcl.2019.04.008", pmid="30981576",
             title="Structure of the human JAK1 kinase domain with compound 39",
             construct_auth="A/B:854-1154", construct_uniprot="854-1154", chain_auth="AB", chain_label="A;B",
             ligand_ccd="KEV", ligand_chain_copy="A", ligand_same_canonical_site="YES_PRIMARY_DEFINITION",
             n_mutation="0", mutations="NONE; 6 expression-tag residues",
             mutation_in_unified_pocket="NO", ptm="PTR1034;PTR1035 on A and B", phosphorylation="PTR_Y1034_Y1035",
             disulfide="0", partner="NONE", retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="2", altloc="YES", n_unobs_res="36", n_unobs_atom="35",
             pocket_unobs="pocket completeness vs alts 1.0",
             clashscore="0.53", percent_rama_outliers="0.00", percent_rota_outliers="0.00",
             validation_source="wwPDB validation XML",
             paper="JAK1 JH1 compound 39",
             conflicts="V4.2 prep uses DOCUMENTED_UNIFORM_PTR_TO_TYR_FALLBACK; deposited structure is PTR",
             historically_exposed="NO", notes="V4.2 primary"),
        dict(target="JAK1", pdb="4EI4", role="ALTERNATIVE", is_primary="NO", uniprot="P23458", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="2.22", doi="10.1021/jm300628c", pmid="22698084",
             title="JAK1 kinase (JH1 domain) in complex with compound 20",
             construct_auth="A/B:854-1154", construct_uniprot="854-1154", chain_auth="A", chain_label="A",
             ligand_ccd="0Q2", ligand_chain_copy="A:1 and B:1", ligand_same_canonical_site="YES_JH1_ATP",
             n_mutation="0", mutations="NONE; 2 expression-tag residues",
             mutation_in_unified_pocket="NO", ptm="PTR1034;PTR1035 on A and B", phosphorylation="PTR_Y1034_Y1035_SAME_AS_PRIMARY",
             disulfide="0", partner="NONE", retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="2", altloc="NO", n_unobs_res="31", n_unobs_atom="0",
             pocket_unobs="pocket completeness 1.0",
             clashscore="5.32", percent_rama_outliers="0.18", percent_rota_outliers="0.78",
             validation_source="wwPDB validation XML",
             paper="JAK1 JH1 compound 20",
             conflicts="Primary extract policy is AB; this alt can use A-only or AB. Must freeze copy before prep.",
             historically_exposed="YES_V1_DISCUSSION", notes="CLEAN-NEAR; same PTR sites as 6N7A"),
        dict(target="JAK2", pdb="8BXH", role="PRIMARY", is_primary="YES", uniprot="O60674", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="1.30", doi="10.1021/acs.jmedchem.4c00197", pmid="38843875",
             title="Crystal structure of JAK2 JH1 in complex with momelotinib",
             construct_auth="A:840-1132", construct_uniprot="840-1132", chain_auth="A", chain_label="A",
             ligand_ccd="C87", ligand_chain_copy="A:1201", ligand_same_canonical_site="YES_PRIMARY_DEFINITION",
             n_mutation="0", mutations="NONE; His-tag expression residues present",
             mutation_in_unified_pocket="NO", ptm="PTR1007;PTR1008", phosphorylation="PTR_Y1007_Y1008",
             disulfide="0", partner="NONE", retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1", altloc="YES", n_unobs_res="16", n_unobs_atom="25",
             pocket_unobs="pocket completeness vs alts 1.0",
             clashscore="5.15", percent_rama_outliers="0.68", percent_rota_outliers="0.38",
             validation_source="wwPDB validation XML",
             paper="2024 JMC JAK2 JH1 momelotinib",
             conflicts="V4.2 PTR->TYR fallback; deposited PTR",
             historically_exposed="NO", notes="V4.2 primary"),
        dict(target="JAK2", pdb="8BM2", role="ALTERNATIVE", is_primary="NO", uniprot="O60674", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="1.50", doi="10.1021/acs.jmedchem.4c00197", pmid="38843875",
             title="Crystal structure of JAK2 JH1 in complex with gandotinib",
             construct_auth="A/B:840-1132", construct_uniprot="840-1132", chain_auth="A", chain_label="A",
             ligand_ccd="QQC", ligand_chain_copy="A and B", ligand_same_canonical_site="YES_JH1_ATP",
             n_mutation="0", mutations="NONE; His-tag differs by one extra Gly vs 8BXH (MGHHHHHH vs MHHHHHH)",
             mutation_in_unified_pocket="NO", ptm="PTR1007;PTR1008 on A and B", phosphorylation="PTR_Y1007_Y1008_SAME_AS_PRIMARY",
             disulfide="0", partner="NONE", retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="2", altloc="YES", n_unobs_res="34", n_unobs_atom="42",
             pocket_unobs="pocket completeness 1.0",
             clashscore="3.59", percent_rama_outliers="0.34", percent_rota_outliers="0.19",
             validation_source="wwPDB validation XML",
             paper="Same 2024 JMC paper as 8BXH",
             conflicts="Pocket perturbation NEAR at 4.0/4.5 A and INTERMEDIATE at 5.0 A (CUTOFF_SENSITIVE). Copy number 2 vs primary 1.",
             historically_exposed="YES_V1_DISCUSSION", notes="CLEAN with cutoff-sensitive pocket bin"),
        dict(target="TYK2", pdb="3LXP", role="PRIMARY", is_primary="YES", uniprot="P29597", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="1.65", doi="10.1016/j.jmb.2010.05.020", pmid="20478313",
             title="Structural and Thermodynamic Characterization of the TYK2 and JAK3 Kinase Domains in Complex with CP-690550 and CMP-6",
             construct_auth="A:888-1182", construct_uniprot="888-1182", chain_auth="A", chain_label="A",
             ligand_ccd="IZA", ligand_chain_copy="A", ligand_same_canonical_site="YES_PRIMARY_DEFINITION",
             n_mutation="5", mutations="C936A; Q969A; E971A; K972A; C1142A",
             mutation_in_unified_pocket="UNKNOWN_not_distance_mapped_in_this_round_for_TYK2_alts",
             ptm="PTR1054", phosphorylation="PTR_Y1054",
             disulfide="0", partner="NONE", retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1", altloc="NO", n_unobs_res="32", n_unobs_atom="64",
             pocket_unobs="UNKNOWN_vs_alts_not_recompared_in_V2_jobs",
             clashscore="UNKNOWN_fetched_yes_not_tabulated_here", percent_rama_outliers="UNKNOWN", percent_rota_outliers="UNKNOWN",
             validation_source="wwPDB validation XML fetched",
             paper="Chrencik 2010 JMB",
             conflicts="Five engineered mutations on primary; V2 did not re-verify 3NZ0/4GVJ mmCIF. JAK1/TYK2 cannot win Family 1 on incomplete V2 verification.",
             historically_exposed="NO", notes="PRIMARY only in V2 fact set; no V2 alt re-verification"),
        dict(target="PIK3CA", pdb="4L23", role="PRIMARY", is_primary="YES", uniprot="P42336", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="2.501", doi="10.1021/ml400378e", pmid="24900786",
             title="Crystal Structure of p110alpha complexed with niSH2 of p85alpha and PI-103",
             construct_auth="A:1-1068; B:318-615", construct_uniprot="p110 1-1068; p85 318-615",
             chain_auth="A", chain_label="A",
             ligand_ccd="X6K", ligand_chain_copy="A:1101/label C", ligand_same_canonical_site="YES_PRIMARY_DEFINITION",
             n_mutation="0", mutations="NONE on p110 or p85; p85 has N-term expression tag",
             mutation_in_unified_pocket="NO", ptm="NONE", phosphorylation="NONE",
             disulfide="0", partner="p85-alpha niSH2 chain B; V4.2 policy REMOVE",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1_p110_plus_p85", altloc="NO", n_unobs_res="101", n_unobs_atom="26",
             pocket_unobs="pocket completeness vs same-p85 alts 1.0",
             clashscore="7.70", percent_rama_outliers="0.08", percent_rota_outliers="11.68",
             validation_source="wwPDB validation XML",
             paper="Zhao 2014 ACS Med Chem Lett PI-103 and analogs",
             conflicts="p85 present in crystal but REMOVE in V4.2 extract",
             historically_exposed="NO", notes="V4.2 primary"),
        dict(target="PIK3CA", pdb="4L2Y", role="ALTERNATIVE", is_primary="NO", uniprot="P42336", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="2.8000", doi="10.1021/ml400378e", pmid="24900786",
             title="Crystal Structure of p110alpha complexed with niSH2 of p85alpha and compound 9d",
             construct_auth="A:1-1068; B:318-615", construct_uniprot="identical_to_4L23",
             chain_auth="A", chain_label="A",
             ligand_ccd="XXK", ligand_chain_copy="A:1", ligand_same_canonical_site="YES_ATP_CATALYTIC_SAME_SERIES_AS_X6K",
             n_mutation="0", mutations="NONE; entity_poly sequences identical to 4L23 on both chains",
             mutation_in_unified_pocket="NO", ptm="NONE", phosphorylation="NONE",
             disulfide="0", partner="p85-alpha niSH2 chain B; same REMOVE policy applies",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1_p110_plus_p85", altloc="NO", n_unobs_res="124", n_unobs_atom="0",
             pocket_unobs="pocket completeness 1.0",
             clashscore="3.63", percent_rama_outliers="0.08", percent_rota_outliers="3.77",
             validation_source="wwPDB validation XML",
             paper="Same Zhao 2014 paper as 4L23; ligand-induced same-construct pair",
             conflicts="NONE vs 4L23 at sequence/construct/partner. V1 omitted this PDB.",
             historically_exposed="NO", notes="CLEAN-NEAR; missed by V1"),
        dict(target="PIK3CA", pdb="4JPS", role="ALTERNATIVE", is_primary="NO", uniprot="P42336", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="2.20", doi="10.1016/j.bmcl.2013.05.007", pmid="23726034",
             title="Co-crystal Structures of the Lipid Kinase PI3K alpha with Pan and Isoform Selective Inhibitors",
             construct_auth="A:1-1068; B:307-593", construct_uniprot="p110 1-1068; p85 307-593",
             chain_auth="A", chain_label="A",
             ligand_ccd="1LT", ligand_chain_copy="A:1", ligand_same_canonical_site="YES_ATP_CATALYTIC",
             n_mutation="2", mutations="M232K; L233K on p110; plus C-term His-tag",
             mutation_in_unified_pocket="NO_not_in_4L23_4.5A_set_772-933",
             ptm="NONE", phosphorylation="NONE",
             disulfide="0", partner="p85-alpha but shorter 307-593 vs 318-615",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1_p110_plus_p85", altloc="YES", n_unobs_res="141", n_unobs_atom="194",
             pocket_unobs="pocket completeness 1.0",
             clashscore="2.47", percent_rama_outliers="0.33", percent_rota_outliers="1.20",
             validation_source="wwPDB validation XML",
             paper="Zhao 2013 BMCL",
             conflicts="p85 boundary and two p110 mutations vs 4L23; historically in analysis_freeze allowed_pdb",
             historically_exposed="YES_MANIFEST_AND_FREEZE", notes="MODERATE-NEAR same-construct-class ligand-induced plus distal mutations"),
        dict(target="PIK3CA", pdb="5XGH", role="ALTERNATIVE", is_primary="NO", uniprot="P42336", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="2.97", doi="10.1038/s41598-017-15260-5", pmid="29109464",
             title="Crystal structure of PI3K complex with an inhibitor",
             construct_auth="A:8-1055; B:322-598", construct_uniprot="truncated vs 4L23",
             chain_auth="A", chain_label="A",
             ligand_ccd="84U", ligand_chain_copy="A:1", ligand_same_canonical_site="YES_ATP_CATALYTIC",
             n_mutation="0", mutations="NONE_IN_entity.pdbx_mutation",
             mutation_in_unified_pocket="NO", ptm="NONE", phosphorylation="NONE",
             disulfide="0", partner="p85 present but 322-598 vs 318-615",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1_p110_plus_p85", altloc="NO", n_unobs_res="55", n_unobs_atom="0",
             pocket_unobs="pocket completeness 1.0",
             clashscore="0.05", percent_rama_outliers="0.00", percent_rota_outliers="1.11",
             validation_source="wwPDB validation XML",
             paper="2017 Sci Rep",
             conflicts="Construct boundaries differ on both p110 and p85",
             historically_exposed="YES_V1_DISCUSSION", notes="MODERATE-NEAR construct-trimmed same partner class"),
        dict(target="PIK3CA", pdb="5DXT", role="ALTERNATIVE", is_primary="NO", uniprot="P42336", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="2.25", doi="10.1021/acs.jmedchem.5b01483", pmid="26741947",
             title="p110alpha with GDC-0326",
             construct_auth="A:107-1068", construct_uniprot="107-1068_no_p85",
             chain_auth="A", chain_label="A",
             ligand_ccd="5H5", ligand_chain_copy="A:1", ligand_same_canonical_site="YES_ATP_CATALYTIC",
             n_mutation="0", mutations="NONE_IN_entity.pdbx_mutation",
             mutation_in_unified_pocket="NO", ptm="NONE", phosphorylation="NONE",
             disulfide="0", partner="NONE_p85_absent",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1_p110_only", altloc="NO", n_unobs_res="83", n_unobs_atom="215",
             pocket_unobs="pocket completeness 1.0 but conformation FAR",
             clashscore="0.14", percent_rama_outliers="0.00", percent_rota_outliers="1.82",
             validation_source="wwPDB validation XML",
             paper="Heffron 2016 JMC GDC-0326",
             conflicts="V1 called INTERMEDIATE; partner absence plus FAR pocket is CONFOUNDED. Historically in allowed_pdb.",
             historically_exposed="YES_MANIFEST_AND_FREEZE", notes="CONFOUNDED-FAR construct/component/state not ligand-only"),
        dict(target="mTOR", pdb="4JT6", role="PRIMARY", is_primary="YES", uniprot="P42345", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="3.6000", doi="10.1038/nature12122", pmid="23636326",
             title="structure of mTORDeltaN-mLST8-PI-103 complex",
             construct_auth="mTOR A/B 1376-2549; mLST8 C/D 1-326", construct_uniprot="1376-2549",
             chain_auth="A", chain_label="C",
             ligand_ccd="X6K", ligand_chain_copy="A:2601 and B:1", ligand_same_canonical_site="YES_PRIMARY_DEFINITION",
             n_mutation="0", mutations="NONE",
             mutation_in_unified_pocket="NO", ptm="NONE", phosphorylation="NONE",
             disulfide="0", partner="mLST8 and second mTOR copy; V4.2 REMOVE extra mTOR and mLST8",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="2_mTOR_plus_2_mLST8", altloc="NO", n_unobs_res="254", n_unobs_atom="0",
             pocket_unobs="254 unobs; pocket vs series alts completeness 1.0",
             clashscore="16.38", percent_rama_outliers="3.74", percent_rota_outliers="11.02",
             validation_source="wwPDB validation XML",
             paper="Yang 2013 Nature mTORdeltaN-mLST8 series",
             conflicts="auth A = label C (frozen). High clashscore typical of this 3.5-3.6 A series.",
             historically_exposed="NO", notes="V4.2 primary"),
        dict(target="mTOR", pdb="4JT5", role="ALTERNATIVE", is_primary="NO", uniprot="P42345", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="3.45", doi="10.1038/nature12122", pmid="23636326",
             title="mTORdeltaN-mLST8-pp242 complex",
             construct_auth="mTOR A/B 1376-2549; mLST8 1-323", construct_uniprot="same_deltaN",
             chain_auth="A", chain_label="C",
             ligand_ccd="P2X", ligand_chain_copy="A:1 and B:1", ligand_same_canonical_site="YES_ATP_SITE_INHIBITOR",
             n_mutation="0", mutations="NONE; 6 expression-tag rows",
             mutation_in_unified_pocket="NO", ptm="NONE", phosphorylation="NONE",
             disulfide="0", partner="same mLST8 background; same REMOVE policy",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="2_mTOR_plus_2_mLST8", altloc="NO", n_unobs_res="254", n_unobs_atom="0",
             pocket_unobs="pocket completeness 1.0",
             clashscore="19.25", percent_rama_outliers="3.67", percent_rota_outliers="12.60",
             validation_source="wwPDB validation XML",
             paper="Same Yang 2013 Nature series; pp242 vs PI-103",
             conflicts="mLST8 declared 1-323 vs 1-326 on 4JT6 (3-residue annotation difference)",
             historically_exposed="YES_V1_DISCUSSION", notes="CLEAN-NEAR same-series inhibitor"),
        dict(target="mTOR", pdb="4JSX", role="ALTERNATIVE", is_primary="NO", uniprot="P42345", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="3.50", doi="10.1038/nature12122", pmid="23636326",
             title="structure of mTORDeltaN-mLST8-Torin2 complex",
             construct_auth="mTOR A/B 1376-2549; mLST8 1-326", construct_uniprot="same_deltaN",
             chain_auth="A", chain_label="C",
             ligand_ccd="17G", ligand_chain_copy="A:1 and B:1", ligand_same_canonical_site="YES_ATP_SITE_INHIBITOR",
             n_mutation="0", mutations="NONE",
             mutation_in_unified_pocket="NO", ptm="NONE", phosphorylation="NONE",
             disulfide="0", partner="same mLST8 background; same REMOVE policy",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="2_mTOR_plus_2_mLST8", altloc="NO", n_unobs_res="254", n_unobs_atom="1",
             pocket_unobs="pocket completeness 1.0",
             clashscore="18.13", percent_rama_outliers="3.15", percent_rota_outliers="11.06",
             validation_source="wwPDB validation XML",
             paper="Same Yang 2013 Nature series; Torin2",
             conflicts="Historically in analysis_freeze allowed_pdb; not excluded for that reason",
             historically_exposed="YES_MANIFEST_AND_FREEZE", notes="CLEAN-NEAR same-series inhibitor"),
        dict(target="mTOR", pdb="4JSV", role="ALTERNATIVE", is_primary="NO", uniprot="P42345", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="3.5000", doi="10.1038/nature12122", pmid="23636326",
             title="mTOR kinase structure, mechanism and regulation.",
             construct_auth="mTOR A/B 1376-2549; mLST8 1-326", construct_uniprot="same_deltaN",
             chain_auth="A", chain_label="C",
             ligand_ccd="ADP", ligand_chain_copy="A:297 and B:297 plus MG/MGF", ligand_same_canonical_site="YES_ATP_SITE_NUCLEOTIDE",
             n_mutation="0", mutations="NONE",
             mutation_in_unified_pocket="NO", ptm="NONE", phosphorylation="NONE",
             disulfide="0", partner="same mLST8 background; same REMOVE policy",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="2_mTOR_plus_2_mLST8", altloc="NO", n_unobs_res="250", n_unobs_atom="0",
             pocket_unobs="pocket completeness 1.0",
             clashscore="14.52", percent_rama_outliers="3.44", percent_rota_outliers="9.62",
             validation_source="wwPDB validation XML",
             paper="Same Yang 2013 Nature series; ADP+Mg not an inhibitor",
             conflicts="Ligand class nucleotide vs ATP-site inhibitor; still same construct",
             historically_exposed="YES_V1_SELECTED_OPTIONAL", notes="CLEAN-NEAR but ligand-class change (ADP vs inhibitor)"),
        dict(target="AChE", pdb="4EY7", role="PRIMARY", is_primary="YES", uniprot="P22303", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="2.3509", doi="10.1021/jm300871x", pmid="23035744",
             title="Crystal Structure of Recombinant Human Acetylcholinesterase in Complex with Donepezil",
             construct_auth="A/B:2-543 maps db33-574", construct_uniprot="33-574",
             chain_auth="AB", chain_label="A;B",
             ligand_ccd="E20", ligand_chain_copy="A:604 BOX_DEFINING; B:605 NON_PRIMARY", ligand_same_canonical_site="YES_PRIMARY_DEFINITION",
             n_mutation="0", mutations="NONE",
             mutation_in_unified_pocket="NO", ptm="N-glycosylation ASN265/ASN350", phosphorylation="NONE",
             disulfide="6_pairs", partner="NONE; biological dimer AB RETAIN",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="2", altloc="YES", n_unobs_res="19", n_unobs_atom="0",
             pocket_unobs="pocket completeness 1.0 vs 4EY6",
             clashscore="2.80", percent_rama_outliers="0.00", percent_rota_outliers="1.50",
             validation_source="wwPDB validation XML",
             paper="Cheung 2012 JMC",
             conflicts="NONE vs 4EY6 at construct/sequence",
             historically_exposed="NO", notes="V4.2 primary"),
        dict(target="AChE", pdb="4EY6", role="ALTERNATIVE", is_primary="NO", uniprot="P22303", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="2.3983", doi="10.1021/jm300871x", pmid="23035744",
             title="Crystal Structure of Recombinant Human Acetylcholinesterase in Complex with (-)-galantamine",
             construct_auth="A/B:2-543 maps db33-574", construct_uniprot="identical_to_4EY7",
             chain_auth="A", chain_label="A",
             ligand_ccd="GNT", ligand_chain_copy="A:1 and B:2", ligand_same_canonical_site="YES_CATALYTIC_GORGE",
             n_mutation="0", mutations="NONE; entity_poly sequence identical to 4EY7",
             mutation_in_unified_pocket="NO", ptm="same N-glycosylation sites as 4EY7", phosphorylation="NONE",
             disulfide="6_pairs_identical", partner="NONE; dimer AB same as primary extract",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="2", altloc="YES", n_unobs_res="19", n_unobs_atom="0",
             pocket_unobs="pocket completeness 1.0",
             clashscore="3.26", percent_rama_outliers="0.00", percent_rota_outliers="1.16",
             validation_source="wwPDB validation XML",
             paper="Same Cheung 2012 paper as 4EY7",
             conflicts="NONE",
             historically_exposed="YES_V1_DISCUSSION", notes="CLEAN-NEAR"),
        dict(target="BChE", pdb="4BDS", role="PRIMARY", is_primary="YES", uniprot="P06276", species="HOMO SAPIENS",
             method="X-RAY DIFFRACTION", resolution="2.100", doi="10.1042/BJ20130013", pmid="23679855",
             title="Human butyrylcholinesterase in complex with tacrine",
             construct_auth="A:1-529 maps db29-557", construct_uniprot="29-557",
             chain_auth="A", chain_label="A",
             ligand_ccd="THA", ligand_chain_copy="A:701", ligand_same_canonical_site="YES_PRIMARY_DEFINITION",
             n_mutation="4", mutations="N45Q(auth17); N483Q(auth455); N481Q_db509(auth481); N486Q_db514(auth486)",
             mutation_in_unified_pocket="NO_not_in_4.5A_set",
             ptm="N-glycosylation at remaining Asn57/106/241/256/341/485", phosphorylation="NONE",
             disulfide="3_pairs", partner="NONE",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1", altloc="YES", n_unobs_res="5", n_unobs_atom="5",
             pocket_unobs="pocket completeness 1.0 vs 1P0M",
             clashscore="5.05", percent_rama_outliers="0.38", percent_rota_outliers="4.69",
             validation_source="wwPDB validation XML",
             paper="Nachon 2013 Biochem J; recombinant low-glycosylation monomer construct",
             conflicts="entity.pdbx_mutation=YES without residue list; struct_ref_seq_dif lists the four N->Q mutations. RCSB page says Mutation(s): 4.",
             historically_exposed="NO", notes="V4.2 primary"),
        dict(target="BChE", pdb="1P0M", role="ALTERNATIVE", is_primary="NO", uniprot="P06276", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="2.38", doi="10.1074/jbc.M210241200", pmid="12869558",
             title="Crystal structure of human butyryl cholinesterase in complex with a choline molecule",
             construct_auth="A:1-529 maps db29-557", construct_uniprot="identical_to_4BDS",
             chain_auth="A", chain_label="A",
             ligand_ccd="CHT", ligand_chain_copy="A:7", ligand_same_canonical_site="YES_CATALYTIC_GORGE",
             n_mutation="4", mutations="N17Q; N455Q; N481Q; N486Q listed in entity.pdbx_mutation; same four struct_ref_seq_dif rows as 4BDS",
             mutation_in_unified_pocket="NO",
             ptm="N-glycosylation Asn57/106/241/341/485 (no Asn256 row in mod_residue)", phosphorylation="NONE",
             disulfide="3_pairs_identical", partner="NONE",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1", altloc="YES", n_unobs_res="6", n_unobs_atom="120",
             pocket_unobs="pocket completeness 1.0; more missing side-chain atoms than 4BDS (120 vs 5)",
             clashscore="12.92", percent_rama_outliers="0.39", percent_rota_outliers="3.80",
             validation_source="wwPDB validation XML",
             paper="Nicolet 2003 JBC choline complex; same engineered glycosylation-site construct",
             conflicts="entity.pdbx_mutation listed on 1P0M vs YES-only on 4BDS; sequences and seq_dif identities match. Glycosylation-site count in mod_residue 5 vs 6.",
             historically_exposed="YES_V1_DISCUSSION", notes="CLEAN-NEAR; mutation background matches"),
        dict(target="F2", pdb="4UDW", role="PRIMARY", is_primary="YES", uniprot="P00734", species="HOMO SAPIENS",
             method="X-RAY DIFFRACTION", resolution="1.160", doi="10.1021/ACS.JMEDCHEM.5B00812", pmid="26270568",
             title="Thrombin in complex with D-Phe-Pro amide",
             construct_auth="H:16-246/db364-621; L:1-14/db333-360; I:555-565/db62-72", construct_uniprot="heavy+light+hirudin_v2",
             chain_auth="HIL", chain_label="H;I;L",
             ligand_ccd="N6L", ligand_chain_copy="H:1249", ligand_same_canonical_site="YES_PRIMARY_DEFINITION",
             n_mutation="0", mutations="NONE",
             mutation_in_unified_pocket="NO",
             ptm="ASN60 glycosylation on H; TYS563 on hirudin I", phosphorylation="NONE",
             disulfide="4_including_H-L", partner="hirudin variant-2 chain I RETAIN; light chain L RETAIN",
             retained_peptide="hirudin_v2_short_Cterm", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1", altloc="YES", n_unobs_res="7", n_unobs_atom="34",
             pocket_unobs="autolysis-loop 147 insertion unobs; F2 pocket completeness metric CONFLICT because insertion numbering",
             clashscore="3.23", percent_rama_outliers="0.00", percent_rota_outliers="0.41",
             validation_source="wwPDB validation XML",
             paper="2015 JMC",
             conflicts="Hirudin UniProt listed as P09945. Autolysis loop 147 multi-occupancy numbering.",
             historically_exposed="NO", notes="V4.2 primary"),
        dict(target="F2", pdb="3SHC", role="ALTERNATIVE", is_primary="NO", uniprot="P00734", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="1.900", doi="10.1016/j.jmb.2012.01.054", pmid="22366545",
             title="Human Thrombin In Complex With UBTHR101",
             construct_auth="H:16-247/db364-622; L:1-15/db328-363; I:53-65/db60-72", construct_uniprot="heavy+light+hirudin_v2",
             chain_auth="H", chain_label="H",
             ligand_ccd="B01", ligand_chain_copy="H:3", ligand_same_canonical_site="YES_CATALYTIC_S1",
             n_mutation="0", mutations="NONE",
             mutation_in_unified_pocket="NO",
             ptm="ASN60 glycosylation on H; TYS63 on hirudin I", phosphorylation="NONE",
             disulfide="4_including_H-L", partner="hirudin variant-2 RETAIN; light chain present",
             retained_peptide="hirudin_v2_longer_Nterm_than_4UDW", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1", altloc="YES", n_unobs_res="18", n_unobs_atom="29",
             pocket_unobs="NEAR pocket CA; insertion-numbering completeness CONFLICT",
             clashscore="4.61", percent_rama_outliers="0.00", percent_rota_outliers="1.63",
             validation_source="wwPDB validation XML",
             paper="2012 JMB UBTHR101",
             conflicts="Hirudin fragment longer (13 vs 11 aa) and light chain N-term longer (36 vs 28). Partner identity hirudin-v2+TYS retained both.",
             historically_exposed="YES_V1_DISCUSSION", notes="MODERATE-NEAR residual peptide-length difference"),
        dict(target="F10", pdb="2JKH", role="PRIMARY", is_primary="YES", uniprot="P00742", species="HOMO SAPIENS",
             method="X-RAY DIFFRACTION", resolution="1.25", doi="10.1002/ANIE.200804695", pmid="19101972",
             title="Factor Xa - cation inhibitor complex",
             construct_auth="A:16-251/db235-475; L:86-140/db126-180", construct_uniprot="heavy 235-475; light 126-180",
             chain_auth="AL", chain_label="A;L",
             ligand_ccd="BI7", ligand_chain_copy="A:1244", ligand_same_canonical_site="YES_PRIMARY_DEFINITION",
             n_mutation="1", mutations="R372E (auth A:150) engineered",
             mutation_in_unified_pocket="NO_auth150_not_in_4.5A_set",
             ptm="NONE_IN_mod_residue", phosphorylation="NONE",
             disulfide="10", partner="light chain L RETAIN",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1", altloc="YES", n_unobs_res="8", n_unobs_atom="6",
             pocket_unobs="pocket completeness 1.0 vs 2Y5F",
             clashscore="2.56", percent_rama_outliers="0.35", percent_rota_outliers="1.23",
             validation_source="wwPDB validation XML",
             paper="Salonen 2009 Angew Chem",
             conflicts="entity.pdbx_mutation=YES without residue; struct_ref_seq_dif has ARG372GLU. Ca2+ present (not in 2Y5F).",
             historically_exposed="NO", notes="V4.2 primary"),
        dict(target="F10", pdb="2Y5F", role="ALTERNATIVE", is_primary="NO", uniprot="P00742", species="HOMO SAPIENS",
             method="X-RAY DIFFRACTION", resolution="1.29", doi="10.1002/CHEM.201102571", pmid="22162109",
             title="FACTOR XA - CATION INHIBITOR COMPLEX",
             construct_auth="A:16-244/db235-468; L:87-140/db127-180", construct_uniprot="heavy 235-468; light 127-180",
             chain_auth="A", chain_label="A",
             ligand_ccd="XWG", ligand_chain_copy="A", ligand_same_canonical_site="YES_S1_S4_CATION_INHIBITOR",
             n_mutation="1", mutations="R372E (auth A:150) SAME as 2JKH; PDB SEQADV GLU A 150 vs UNP ARG 372",
             mutation_in_unified_pocket="NO",
             ptm="NONE_IN_mod_residue", phosphorylation="NONE",
             disulfide="10", partner="light chain present; RETAIN policy applies",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1", altloc="YES", n_unobs_res="0", n_unobs_atom="6",
             pocket_unobs="pocket completeness 1.0",
             clashscore="1.92", percent_rama_outliers="0.35", percent_rota_outliers="0.00",
             validation_source="wwPDB validation XML",
             paper="Salonen 2011 Chem Eur J same cation-inhibitor series",
             conflicts="Heavy C-term 468 vs 475; light starts 127 vs 126; no CA ion listed vs 2JKH CA. Mutation identity MATCHES (not merely both-mutated).",
             historically_exposed="YES_V1_DISCUSSION", notes="CLEAN-NEAR / slight construct-end difference"),
        dict(target="PPARG", pdb="9V8H", role="PRIMARY", is_primary="YES", uniprot="P37231", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="1.39", doi="10.1021/jacs.5c13803", pmid="41188059",
             title="PPARgamma ligand-binding domain in complex with PG08-NL and rosiglitazone",
             construct_auth="A:203-477/db231-505; B:1-20 peptide", construct_uniprot="LBD 231-505",
             chain_auth="AB", chain_label="A;B",
             ligand_ccd="BRL", ligand_chain_copy="A:501", ligand_same_canonical_site="YES_PRIMARY_DEFINITION",
             n_mutation="0", mutations="NONE",
             mutation_in_unified_pocket="NO", ptm="NONE", phosphorylation="NONE",
             disulfide="0", partner="PG08-NL peptide B RETAIN",
             retained_peptide="PG08-NL", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1_LBD_plus_peptide", altloc="YES", n_unobs_res="29", n_unobs_atom="4",
             pocket_unobs="pocket vs 7AWC completeness 1.0 but FAR",
             clashscore="7.43", percent_rama_outliers="0.00", percent_rota_outliers="0.86",
             validation_source="wwPDB validation XML",
             paper="2025 JACS peptide+rosiglitazone",
             conflicts="struct_ref lists 9V8H as peptide accession (not UniProt)",
             historically_exposed="NO", notes="V4.2 primary"),
        dict(target="PPARG", pdb="7AWC", role="ALTERNATIVE", is_primary="NO", uniprot="P37231", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="1.7400", doi="10.1016/j.chembiol.2021.04.019", pmid="33989565",
             title="Crystal structure of PPARG in complex with rosiglitazone",
             construct_auth="A:203-477/db231-505", construct_uniprot="LBD_same_range_no_peptide",
             chain_auth="A", chain_label="A",
             ligand_ccd="BRL", ligand_chain_copy="A:1", ligand_same_canonical_site="YES_LBD",
             n_mutation="0", mutations="NONE; 2 expression-tag rows",
             mutation_in_unified_pocket="NO", ptm="NONE", phosphorylation="NONE",
             disulfide="0", partner="NONE_PG08NL_absent",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1_LBD_only", altloc="YES", n_unobs_res="6", n_unobs_atom="3",
             pocket_unobs="completeness 1.0; AF-2/H12 class motion implied by FAR 5.6 A",
             clashscore="5.89", percent_rama_outliers="0.00", percent_rota_outliers="0.41",
             validation_source="wwPDB validation XML",
             paper="2021 Cell Chem Biol binary BRL",
             conflicts="V1 INTERMEDIATE; peptide removal plus FAR pocket is CONFOUNDED. Manifest declined 7AWC.",
             historically_exposed="YES_MANIFEST_DECLINED_AND_V1", notes="CONFOUNDED-FAR; no CLEAN PPARG alt"),
        dict(target="PPARA", pdb="6LXA", role="PRIMARY", is_primary="YES", uniprot="Q07869", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="1.2300", doi="10.1016/j.isci.2020.101727", pmid="33205029",
             title="PPARalpha LBD-EPA co-crystals",
             construct_auth="A:200-468", construct_uniprot="200-468",
             chain_auth="A", chain_label="A",
             ligand_ccd="EPA", ligand_chain_copy="A:502/label C", ligand_same_canonical_site="YES_PRIMARY_DEFINITION",
             n_mutation="0", mutations="NONE; 4 N-term expression-tag rows",
             mutation_in_unified_pocket="NO", ptm="NONE", phosphorylation="NONE",
             disulfide="0", partner="NONE",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1", altloc="YES", n_unobs_res="4", n_unobs_atom="3",
             pocket_unobs="pocket completeness 1.0 vs 6KAX",
             clashscore="UNKNOWN_fetched", percent_rama_outliers="UNKNOWN", percent_rota_outliers="UNKNOWN",
             validation_source="wwPDB validation XML fetched",
             paper="Kamata 2020 iScience delipidation/cross-seeding campaign",
             conflicts="NONE vs 6KAX construct",
             historically_exposed="NO", notes="V4.2 primary; also shared with PPARG/PPARA pair"),
        dict(target="PPARA", pdb="6KAX", role="ALTERNATIVE", is_primary="NO", uniprot="Q07869", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="1.230", doi="10.1016/j.isci.2020.101727", pmid="33205029",
             title="PPARalpha LBD-intrinsic fatty acid co-crystals",
             construct_auth="A:200-468", construct_uniprot="identical_to_6LXA",
             chain_auth="A", chain_label="A",
             ligand_ccd="PLM", ligand_chain_copy="A", ligand_same_canonical_site="YES_LBD",
             n_mutation="0", mutations="NONE; same 4 expression-tag rows",
             mutation_in_unified_pocket="NO", ptm="NONE", phosphorylation="NONE",
             disulfide="0", partner="NONE",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="1", altloc="YES", n_unobs_res="8", n_unobs_atom="11",
             pocket_unobs="pocket completeness 1.0",
             clashscore="UNKNOWN_fetched", percent_rama_outliers="UNKNOWN", percent_rota_outliers="UNKNOWN",
             validation_source="wwPDB validation XML fetched",
             paper="Same Kamata 2020 campaign; palmitate vs EPA",
             conflicts="NONE",
             historically_exposed="YES_V1_DISCUSSION", notes="CLEAN-NEAR"),
        dict(target="PPARD", pdb="5U3Q", role="PRIMARY", is_primary="YES", uniprot="Q03181", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="1.500", doi="10.1073/pnas.1621513114", pmid="28320959",
             title="Human PPARdelta LBD complexed with specific agonist 1",
             construct_auth="A/B:170-441 maps db131-402", construct_uniprot="131-402",
             chain_auth="B", chain_label="B",
             ligand_ccd="7UJ", ligand_chain_copy="B:501/label N (also A:464)", ligand_same_canonical_site="YES_PRIMARY_DEFINITION",
             n_mutation="0", mutations="NONE",
             mutation_in_unified_pocket="NO", ptm="NONE", phosphorylation="NONE",
             disulfide="0", partner="NONE; copy A is LEGACY_ONLY",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="2", altloc="YES", n_unobs_res="8", n_unobs_atom="0",
             pocket_unobs="pocket completeness 1.0 vs 5U46",
             clashscore="2.27", percent_rama_outliers="UNKNOWN", percent_rota_outliers="0.63",
             validation_source="wwPDB validation XML",
             paper="Wu 2017 PNAS",
             conflicts="Two copies; V4.2 freezes B only",
             historically_exposed="NO", notes="V4.2 primary copy B"),
        dict(target="PPARD", pdb="5U46", role="ALTERNATIVE", is_primary="NO", uniprot="Q03181", species="Homo sapiens",
             method="X-RAY DIFFRACTION", resolution="2.000", doi="10.1073/pnas.1621513114", pmid="28320959",
             title="Human PPARdelta LBD complexed with GW501516",
             construct_auth="A/B:170-441 maps db131-402", construct_uniprot="identical_to_5U3Q",
             chain_auth="A", chain_label="A",
             ligand_ccd="7T1", ligand_chain_copy="A:464 and B:464; B7G also present as detergent",
             ligand_same_canonical_site="YES_LBD",
             n_mutation="0", mutations="NONE",
             mutation_in_unified_pocket="NO", ptm="NONE", phosphorylation="NONE",
             disulfide="0", partner="NONE",
             retained_peptide="NONE", apo_holo="HOLO", covalent="NONCOVALENT",
             n_protein_copies="2", altloc="YES", n_unobs_res="16", n_unobs_atom="0",
             pocket_unobs="pocket completeness 1.0",
             clashscore="0.56", percent_rama_outliers="0.00", percent_rota_outliers="0.64",
             validation_source="wwPDB validation XML",
             paper="Same Wu 2017 PNAS; GW501516 vs agonist 1",
             conflicts="First-pass V2 ligand inference incorrectly picked B7G (heptyl glucoside). Orthosteric agonist is 7T1. Pocket RMSD used primary 7UJ residue set so comparison remains valid.",
             historically_exposed="YES_V1_DISCUSSION", notes="CLEAN-NEAR"),
    ]

    # Nuisance matrix pairs
    def yn(v):
        return v

    pairs = [
        dict(target="EGFR", primary_pdb="3POZ", alt_pdb="1XKK",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="NEAR_YES_Nterm_tag_only", same_partner_background="YES",
             same_mutation_state="YES", same_PTMs="YES", same_protein_copy_definition="YES",
             same_component_policy="YES_kinase_only", same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="YES_alphaC_0.58_Aloop_0.52",
             pocket_complete_primary="YES", pocket_complete_alternative="YES",
             comparability_tier="CLEAN", pocket_perturbation="NEAR",
             pocket_perturbation_cutoff_note="NEAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="holo_conformation_sensitivity"),
        dict(target="HER2", primary_pdb="3RCD", alt_pdb="3PP0",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="CONFLICT_range_annotation_differs_sequence_identical",
             same_partner_background="YES_extract_kinase_only_NO_crystal_dimer_vs_tetramer",
             same_mutation_state="CONFLICT_LABEL_SAME_SEQUENCE",
             same_PTMs="YES", same_protein_copy_definition="NO_4_vs_2",
             same_component_policy="YES_kinase_only", same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="NO_alphaC_8.61_Aloop_3.71_core_15.26",
             pocket_complete_primary="YES_with_many_unobs_elsewhere", pocket_complete_alternative="YES",
             comparability_tier="MODERATE", pocket_perturbation="FAR",
             pocket_perturbation_cutoff_note="FAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="broader_receptor_representation_plus_large_conformation"),
        dict(target="JAK1", primary_pdb="6N7A", alt_pdb="4EI4",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="YES_854-1154", same_partner_background="YES",
             same_mutation_state="YES", same_PTMs="YES_PTR1034_1035",
             same_protein_copy_definition="YES_both_AB_if_A_only_frozen",
             same_component_policy="YES_JH1", same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="YES_Aloop_1.62",
             pocket_complete_primary="YES", pocket_complete_alternative="YES",
             comparability_tier="CLEAN", pocket_perturbation="NEAR",
             pocket_perturbation_cutoff_note="NEAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="holo_conformation_sensitivity"),
        dict(target="JAK2", primary_pdb="8BXH", alt_pdb="8BM2",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="YES_840-1132_His_tag_one_Gly_diff",
             same_partner_background="YES", same_mutation_state="YES",
             same_PTMs="YES_PTR1007_1008", same_protein_copy_definition="NO_1_vs_2",
             same_component_policy="YES_JH1", same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="YES_at_4.5_CUTOFF_SENSITIVE_at_5.0",
             pocket_complete_primary="YES", pocket_complete_alternative="YES",
             comparability_tier="CLEAN", pocket_perturbation="NEAR_at_4.0_4.5__INTERMEDIATE_at_5.0",
             pocket_perturbation_cutoff_note="CUTOFF_SENSITIVE",
             historically_exposed_candidate="YES",
             interpretation="holo_conformation_sensitivity_with_copy_nuisance"),
        dict(target="PIK3CA", primary_pdb="4L23", alt_pdb="4L2Y",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="YES_identical_sequences", same_partner_background="YES_p85_same_REMOVE",
             same_mutation_state="YES", same_PTMs="YES", same_protein_copy_definition="YES",
             same_component_policy="YES", same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="YES",
             pocket_complete_primary="YES", pocket_complete_alternative="YES",
             comparability_tier="CLEAN", pocket_perturbation="NEAR",
             pocket_perturbation_cutoff_note="NEAR at 4.0/4.5/5.0",
             historically_exposed_candidate="NO",
             interpretation="holo_conformation_sensitivity"),
        dict(target="PIK3CA", primary_pdb="4L23", alt_pdb="4JPS",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="NO_p85_307-593_vs_318-615", same_partner_background="YES_p85_present_REMOVE",
             same_mutation_state="NO_M232K_L233K", same_PTMs="YES", same_protein_copy_definition="YES",
             same_component_policy="YES", same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="YES_pocket_NEAR",
             pocket_complete_primary="YES", pocket_complete_alternative="YES",
             comparability_tier="MODERATE", pocket_perturbation="NEAR",
             pocket_perturbation_cutoff_note="NEAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="broader_receptor_representation_sensitivity"),
        dict(target="PIK3CA", primary_pdb="4L23", alt_pdb="5XGH",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="NO_p110_8-1055_p85_322-598", same_partner_background="YES_p85_present_REMOVE",
             same_mutation_state="YES", same_PTMs="YES", same_protein_copy_definition="YES",
             same_component_policy="YES", same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="YES_pocket_NEAR",
             pocket_complete_primary="YES", pocket_complete_alternative="YES",
             comparability_tier="MODERATE", pocket_perturbation="NEAR",
             pocket_perturbation_cutoff_note="NEAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="broader_receptor_representation_sensitivity"),
        dict(target="PIK3CA", primary_pdb="4L23", alt_pdb="5DXT",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="NO_107-1068", same_partner_background="NO_p85_absent",
             same_mutation_state="YES", same_PTMs="YES", same_protein_copy_definition="NO",
             same_component_policy="NO_no_p85_to_remove", same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="NO_FAR_pocket",
             pocket_complete_primary="YES", pocket_complete_alternative="YES",
             comparability_tier="CONFOUNDED", pocket_perturbation="FAR",
             pocket_perturbation_cutoff_note="FAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="broader_receptor_representation_sensitivity"),
        dict(target="mTOR", primary_pdb="4JT6", alt_pdb="4JT5",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="YES_deltaN_mLST8_1-323_vs_1-326", same_partner_background="YES_REMOVE_policy",
             same_mutation_state="YES", same_PTMs="YES", same_protein_copy_definition="YES",
             same_component_policy="YES", same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="YES",
             pocket_complete_primary="YES", pocket_complete_alternative="YES",
             comparability_tier="CLEAN", pocket_perturbation="NEAR",
             pocket_perturbation_cutoff_note="NEAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="holo_conformation_sensitivity"),
        dict(target="mTOR", primary_pdb="4JT6", alt_pdb="4JSX",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="YES", same_partner_background="YES_REMOVE_policy",
             same_mutation_state="YES", same_PTMs="YES", same_protein_copy_definition="YES",
             same_component_policy="YES", same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="YES",
             pocket_complete_primary="YES", pocket_complete_alternative="YES",
             comparability_tier="CLEAN", pocket_perturbation="NEAR",
             pocket_perturbation_cutoff_note="NEAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="holo_conformation_sensitivity"),
        dict(target="mTOR", primary_pdb="4JT6", alt_pdb="4JSV",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="YES", same_partner_background="YES_REMOVE_policy",
             same_mutation_state="YES", same_PTMs="YES", same_protein_copy_definition="YES",
             same_component_policy="YES", same_ligand_site="YES_nucleotide_vs_inhibitor",
             same_covalent_state="YES",
             same_major_activation_state="YES",
             pocket_complete_primary="YES", pocket_complete_alternative="YES",
             comparability_tier="CLEAN", pocket_perturbation="NEAR",
             pocket_perturbation_cutoff_note="NEAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="holo_conformation_sensitivity_ligand_class_ADP"),
        dict(target="AChE", primary_pdb="4EY7", alt_pdb="4EY6",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="YES_identical_sequence", same_partner_background="YES_dimer_AB",
             same_mutation_state="YES", same_PTMs="YES", same_protein_copy_definition="YES",
             same_component_policy="YES", same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="YES",
             pocket_complete_primary="YES", pocket_complete_alternative="YES",
             comparability_tier="CLEAN", pocket_perturbation="NEAR",
             pocket_perturbation_cutoff_note="NEAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="holo_conformation_sensitivity"),
        dict(target="BChE", primary_pdb="4BDS", alt_pdb="1P0M",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="YES_identical_sequence", same_partner_background="YES",
             same_mutation_state="YES_same_four_NQ", same_PTMs="NEAR_YES_glyco_count_5_vs_6",
             same_protein_copy_definition="YES",
             same_component_policy="YES", same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="YES",
             pocket_complete_primary="YES", pocket_complete_alternative="YES_more_unobs_atoms",
             comparability_tier="CLEAN", pocket_perturbation="NEAR",
             pocket_perturbation_cutoff_note="NEAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="holo_conformation_sensitivity"),
        dict(target="F2", primary_pdb="4UDW", alt_pdb="3SHC",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="NO_hirudin_and_light_Nterm_length",
             same_partner_background="YES_hirudin_v2_TYS_and_light_retained",
             same_mutation_state="YES", same_PTMs="YES_TYS_hirudin_ASN60",
             same_protein_copy_definition="YES",
             same_component_policy="YES_RETAIN_hirudin", same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="YES",
             pocket_complete_primary="CONFLICT_147_insertion_numbering",
             pocket_complete_alternative="CONFLICT_147_insertion_numbering",
             comparability_tier="MODERATE", pocket_perturbation="NEAR",
             pocket_perturbation_cutoff_note="NEAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="holo_conformation_sensitivity_with_peptide_length_nuisance"),
        dict(target="F10", primary_pdb="2JKH", alt_pdb="2Y5F",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="NEAR_YES_Cterm_468_vs_475_light_127_vs_126",
             same_partner_background="YES_light_RETAIN",
             same_mutation_state="YES_same_R372E", same_PTMs="YES",
             same_protein_copy_definition="YES",
             same_component_policy="YES", same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="YES",
             pocket_complete_primary="YES", pocket_complete_alternative="YES",
             comparability_tier="CLEAN", pocket_perturbation="NEAR",
             pocket_perturbation_cutoff_note="NEAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="holo_conformation_sensitivity"),
        dict(target="PPARG", primary_pdb="9V8H", alt_pdb="7AWC",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="YES_LBD", same_partner_background="NO_PG08NL_absent",
             same_mutation_state="YES", same_PTMs="YES", same_protein_copy_definition="NO",
             same_component_policy="NO_peptide_RETAIN_cannot_be_kept",
             same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="NO_AF2_FAR",
             pocket_complete_primary="YES", pocket_complete_alternative="YES",
             comparability_tier="CONFOUNDED", pocket_perturbation="FAR",
             pocket_perturbation_cutoff_note="FAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="broader_receptor_representation_sensitivity"),
        dict(target="PPARA", primary_pdb="6LXA", alt_pdb="6KAX",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="YES", same_partner_background="YES_no_peptide",
             same_mutation_state="YES", same_PTMs="YES", same_protein_copy_definition="YES",
             same_component_policy="YES", same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="YES",
             pocket_complete_primary="YES", pocket_complete_alternative="YES",
             comparability_tier="CLEAN", pocket_perturbation="NEAR",
             pocket_perturbation_cutoff_note="NEAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="holo_conformation_sensitivity"),
        dict(target="PPARD", primary_pdb="5U3Q", alt_pdb="5U46",
             same_target="YES", same_binding_site="YES", same_species="YES", same_domain="YES",
             same_construct_boundary="YES", same_partner_background="YES_no_peptide",
             same_mutation_state="YES", same_PTMs="YES",
             same_protein_copy_definition="NO_primary_uses_B_alt_uses_A",
             same_component_policy="YES_do_not_use_5U3Q_A",
             same_ligand_site="YES", same_covalent_state="YES",
             same_major_activation_state="YES",
             pocket_complete_primary="YES", pocket_complete_alternative="YES",
             comparability_tier="CLEAN", pocket_perturbation="NEAR",
             pocket_perturbation_cutoff_note="NEAR at 4.0/4.5/5.0",
             historically_exposed_candidate="YES",
             interpretation="holo_conformation_sensitivity"),
    ]

    # Availability: verified rows + V1 inventory summaries
    avail = []
    for rec in facts:
        t = rec["target"]
        avail.append({
            "record_type": "VERIFIED_STRUCTURE",
            "target": t, "uniprot": rec["uniprot"], "primary_pdb": PRI[t],
            "pdb_id": rec["pdb"], "role": rec["role"],
            "comparability_tier": "PRIMARY" if rec["is_primary"] == "YES" else "SEE_NUISANCE_MATRIX",
            "experiment_method": rec["method"], "resolution": rec["resolution"],
            "construct": rec["construct_auth"], "chain_auth": rec["chain_auth"],
            "ligand_ccd": rec["ligand_ccd"], "mutations": rec["mutations"],
            "ptm": rec["ptm"], "partner": rec["partner"],
            "historically_exposed_candidate": rec["historically_exposed"],
            "conflicts": rec["conflicts"], "notes": rec["notes"],
            "v1_hard_pass_alts_not_reverified": "",
        })
    for t, (nrows, hp, alts) in V1_INV.items():
        avail.append({
            "record_type": "V1_INVENTORY_SUMMARY_NOT_RESEARCHED",
            "target": t, "uniprot": UNP[t], "primary_pdb": PRI[t],
            "pdb_id": "", "role": "INVENTORY",
            "comparability_tier": "NOT_REVERIFIED",
            "experiment_method": "", "resolution": "",
            "construct": "", "chain_auth": "",
            "ligand_ccd": "", "mutations": "",
            "ptm": "", "partner": "",
            "historically_exposed_candidate": "NA",
            "conflicts": "V2 did not re-query RCSB for new PDBs",
            "notes": f"V1_rows={nrows}; V1_hard_pass_including_primary={hp}; V1_hard_pass_alts={alts}",
            "v1_hard_pass_alts_not_reverified": str(alts),
        })

    struct_rows = []
    prim_chain = {
        "EGFR": ("3POZ", "A"), "HER2": ("3RCD", "A"), "JAK1": ("6N7A", "A"),
        "JAK2": ("8BXH", "A"), "PIK3CA": ("4L23", "A"), "mTOR": ("4JT6", "A"),
        "AChE": ("4EY7", "A"), "BChE": ("4BDS", "A"), "F2": ("4UDW", "H"),
        "F10": ("2JKH", "A"), "PPARG": ("9V8H", "A"), "PPARA": ("6LXA", "A"),
        "PPARD": ("5U3Q", "B"),
    }
    alt_chain = {
        "1XKK": "A", "3PP0": "B", "4EI4": "A", "8BM2": "A", "4L2Y": "A",
        "4JPS": "A", "5XGH": "A", "5DXT": "A", "4JT5": "A", "4JSX": "A",
        "4JSV": "A", "4EY6": "A", "1P0M": "A", "3SHC": "H", "2Y5F": "A",
        "7AWC": "A", "6KAX": "A", "5U46": "A",
    }
    for (t, alt, cut), (bb, sc, npk, ncom, comp, nrot, pert) in RMSD.items():
        ppdb, pauth = prim_chain[t]
        struct_rows.append({
            "target": t, "primary_pdb": ppdb, "primary_chain": pauth,
            "alt_pdb": alt, "alt_chain": alt_chain[alt],
            "pocket_definition": "primary_cognate_any_heavy_atom_distance",
            "cutoff_A": cut, "pocket_cutoff_frozen_in_protocol": "NO",
            "n_pocket_primary": npk, "n_common": ncom, "completeness": comp,
            "bb_ca_rmsd": bb, "sidechain_heavy_rmsd": sc,
            "n_rotamer_cb_gt_1.2": nrot,
            "pocket_perturbation": pert,
            "bin_rule": "NEAR<1.5; INTERMEDIATE<=3.0; FAR>3.0 predeclared",
            "same_residue_set_for_all_alts_of_target": "YES",
        })

    wcsv(QA / "ALTERNATIVE_RECEPTOR_FACT_VERIFICATION_V2.csv", facts)
    wcsv(QA / "ALTERNATIVE_RECEPTOR_NUISANCE_MATRIX_V2.csv", pairs)
    wcsv(QA / "ALTERNATIVE_RECEPTOR_STRUCTURAL_COMPARISON_V2.csv", struct_rows)
    wcsv(QA / "ALTERNATIVE_RECEPTOR_AVAILABILITY_AUDIT_V2.csv", avail)
    print("facts", len(facts), "pairs", len(pairs), "struct", len(struct_rows), "avail", len(avail))


if __name__ == "__main__":
    main()
