# UNUSED — not production.
# Current models: independent XGBoost (URAT1 regression SI-only; NLRP3 classifier for shrink).
# MiniMol / reliability fusion / generative rewards were not implemented.
unused: true
